spring:
  application:
    name: spring.test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true  # http://localhost:8080/h2-console 에서 DB 확인 가능

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 시작 시 테이블 자동 생성
    show-sql: true      # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true  # SQL 이쁘게 출력
